### ISSUE TITLE
Повторная отправка КП

### ISSUE THREAD

**Issue by apbubnov** [apbubnov/com_gm_ceiling#51]
- [ ] автоматическая повторная отправка коммерческого предложения, если оно не было просмотрено в течение недели

**Comment by x-DeH4uK-x** [comment]
1ca047d6c2e5ba07dcd79c5341cdc7cbe171250d

**Comment by x-DeH4uK-x** [comment]
b741a7968eb91bc82df043c289d2827d3f960688
